server_port: 10086
server_ip: "127.0.0.1"
mysql_ip: "127.0.0.1"
mysql_port: 3306
mysql_user: "root"
mysql_pwd: "123456"
mysql_db: "AccessDB"
current_dir: "D:\\work\\cube-studio\\AccessMgt\\AccessMgtServer"